# Generated by Django 4.1.7 on 2023-04-25 19:48

from django.db import migrations, models

def set_client_name_default(apps, schema_editor):
    Task = apps.get_model('Agile_Project', 'Task')
    Task.objects.filter(client_name=None).update(client_name='')

class Migration(migrations.Migration):

    dependencies = [
        ('Agile_Project', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_name',
            field= models.CharField(max_length=100, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(set_client_name_default),
    ]