# Generated by Django 4.1.7 on 2023-04-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agile_Project', '0004_remove_task_description_remove_task_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('code', models.CharField(default='', max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('retailer', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
