# Generated by Django 4.1.7 on 2023-04-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agile_Project', '0005_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='retailer',
            new_name='manufacturer',
        ),
    ]
