# Generated by Django 4.1.7 on 2023-04-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agile_Project', '0006_rename_retailer_material_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('item_purchased', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
        ),
    ]
